### ISSUE TITLE
Error when running Sudoku-Solver

### ISSUE THREAD

**Issue by coop44483** [1nfinityLoop/Sudoku-Solver-AI#1]
Using Raspberry Pi 4 Buster OS, Pyton 3.7
OpenCV 4.5, Tensorflow 2.2.2

I changed lines 4 and 5 to
from tensorflow.keras.models import load_model
from tensorflow.keras.models import model_from_json

When I run it I get this error
Traceback (most recent call last):
  File "/home/pi/Desktop/Soduku/sudoku.py", line 8, in <module>
    classifier = load_model("./digit_model.h5")
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/save.py", line 184, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 178, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/serialization.py", line 109, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 373, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py", line 398, in from_config
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/serialization.py", line 109, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 375, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 655, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 599, in __init__
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 125, in __init__
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 294, in __init__
    generic_utils.validate_kwargs(kwargs, allowed_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 792, in validate_kwargs
    raise TypeError(error_message, kwarg)
TypeError: ('Keyword argument not understood:', 'groups')

What Have I missed? or forgotten to do?
Thank you

**Comment by CyberDepot** [comment]
i Check output.avi file and i found this frame

![Image](https://github.com/user-attachments/assets/13cb5245-3813-41ac-b181-fe19fb7bd34c)
